import React from "react";
import { View, Text, StyleSheet, Image, TouchableOpacity } from "react-native";
import { useRouter } from "expo-router";

export const translateTeamName = (name: string): string => {
  const translations: { [key: string]: string } = {
    "Paris Saint Germain": "PSG",
    "1899 Hoffenheim": "Hoffenheim",
    "FC Volendam": "Volendam",
    "Istanbul Basaksehir": "Basaksehir",
    "Al-Qadisiyah FC": "Al Qadsiah",
    "Al-Ahli Jeddah": "Al Ahli",
    "Suwon City FC": "Suwon FC",
    "Al Wahda FC": "Al Wahda",
    "Al-Ittihad FC": "Al Ittihad",
    "FC St. Pauli": "St. Pauli",
    "FC Augsburg": "Augsburg",
    "Gimcheon Sangmu FC": "Gimcheon",
    "NEC Nijmegen": "NEC",
    "GO Ahead Eagles": "GA Eagles",
    "Manchester United": "Man United",
    "Al-Hilal Saudi FC": "Al Hilal",
    "Coquimbo Unido": "Coquimbo",
    "Paris Saint-Germain": "PSG",
    "Olympique de Marseille": "OM",
    "Mali W": "Mali",
    "South Africa W": "Afrique du Sud",
    "Ghana W": "Ghana",
    "Rapid Vienna": "Rapid Vienne",
    "Slovenia": "Slovenie",
    "Sweden": "Suède",
    "Switzerland": "Suisse",
     "Iceland W": "Islande",
    "Greece": "Grèce",
    "Belarus": "Biélorussie",
    "Iceland": "Islande",
    "Tanzania W": "Tanzanie",
    "Switzerland W": "Suisse",
    "Sweden W": "Suède",
    "Dinamo Minsk": "Din.Minsk",
    "Bayern München": "Bayern",
    "FK Zalgiris Vilnius": "FK Zalgiris",
    "West Ham United U21": "West Ham 21",
    "Boreham Wood": "Boreham",
    "Hamrun Spartans": "Hamrun",
    "Hebburn Town": "Hebburn",
    "Spennymoor Town": "Spennymoor",
    "IFK Norrkoping": "Norrkoping",
    "IF Brommapojkarna": "Bromapojkarna",
    "Poland W": "Pologne",
    "Seattle Sounders": "Seattle",
    "Egnatia Rrogozhinë": "Egnatia",
    "Columbus Crew": "Columbus",
    "Haverfordwest County AFC": "Haverfordwest",
    "Bogota FC": "Bogota",
    "Vikingur Gota": "Vikingur",
    "Deportes Copiapo": "Copiapo",
    "Sevilla": "FC Séville",
    "Georgia": "Georgie",
    "Malta": "Malte",
    "Lithuania": "Lituanie",
    "Northern Ireland": "Irlande du Nord",
    "Bulgaria": "Bulgarie",
    "Slovakia": "Slovaquie",
    "Athletic Club": "Ath. Bilbao",
    "Rot-Weiß Essen": "RW Essen",
    "Moldova": "Moldavie",
    "Italy": "Italie",
    "Estonia": "Estonie",
    "Faroe Islands": "Ile Féroé",
    "Türkiye": "Turquie",
    "SC Braga": "Braga",
    "Denmark W": "Danemark",
    "FC Copenhagen": "Copenhague",
    "Borussia Mönchengladbach": "M'gladbach",
    "Avispa Fukuoka": "Fukuoka",
    "Shimizu S-pulse": "Shimizu",
    "Yokohama F. Marinos": "Yokohama",
    "Kawazaki Frontale": "Kawazaki",
    "FC Nordsjaelland": "Nordsjaelland",
    "Union San Felipe": "San Filipe",
    "Rangers de Talca": "Rangers Talca",
    "Deportes Santa Cruz": "Santa Cruz",
    "Universidad de Chile": "U.de Chile",
    "Atletico Madrid": "Atl. Madrid",
    "Everton de Vina": "Everton",
    "HNK Hajduk Split": "Hajduk",
    "Istra 1961": "Istra",
    "NK Slaven Belupo": "Slaven",
    "HNK Rijeka": "Rijeka",
    "Union La Calera": "U. Calera",
    "Mineros de Zacatecas": "Mineros",
    "Stade Brestois 29": "Brest",
    "San Marcos de Arica": "Arica",
    "Los Angeles Galaxy": "LA Galaxy",
    "Deportes Tolima": "D. Tolima",
    "Alianza Petrolera": "Alianza",
    "Maccabi Tel Aviv": "M. Tel Aviv",
    "AFC Hermannstadt": "Hermannstadt",
    "Red Bull Salzburg": "RB Salzburg ",
    "Nottingham Forest": "Nottingham",
    "Independiente Medellin": "Ind. Medellin",
    "Flora Tallinn": "Flora",
    "Kalju Nomme": "Kalju",
    "Kristiansund BK": "Kristiansund",
    "BK Hacken": "Hacken",
    "FC Midtjylland": "Midtjylland",
    "New York City FC": "New York City",
    "Germany W": "Allemagne",
    "Germany M": "Allemagne",
    "Hammarby FF": "Hammarby",
    "Algeria W": "Algerie",
    "Deportes Temuco": "Temuco",
    "Nigeria W": "Nigeria",
    "Fortaleza FC": "Fortaleza",
    "Dinamo Bucuresti": "D. Bucarest",
    "FC Botosani": "Botosani",
    "Zambia W": "Zambie",
    "Netherlands W": "Pays-Bas",
    "Deportivo Laferrere": "Laferrere",
    "Universidad de Concepcion": "U. de Concepcion",
    "Wales W": "Pays de Galles",
    "Belgium W": "Belgique",
    "Portugal W": "Portugal",
    "Spain W": "Espagne",
    "Italy W": "Italie",
    "Santiago Morning": "S.Morning",
    "Norway W": "Norvège", 
    "Finland W": "Finlande",
    "Borussia Dortmund": "Dortmund",
    "RB Leipzig": "Leipzig",
    "Bayer Leverkusen": "Leverkusen",
    "Arsenal FC": "Arsenal",
    "Chelsea FC": "Chelsea",
    "England W": "Angleterre",
    "Liverpool FC": "Liverpool",
    "Cape Verde Islands": "Cap-Vert",
    "Ethiopia": "Ethiopie",
    "GKS Katowice W": "Katowice F",
    "MB Rouisset": "Rouisset",
    "RED Star FC 93": "Red Star",
    "Twente W": "Twente F",
    "Atletico Madrid W": "Atletico Madrid F",
    "Eintracht Frankfurt W": "Frankfort F",
    "Roma W": "Roma F",
    "Sporting CP W": "Sporting F",
    "Paris FC W": "Paris FC F",
    "Manchester United W": "Man United F",
    "Brann W": "Brann F",
    "Austria Wien W": "Autria Vienne F",
    "Vorskla Poltava W": "Vorskla Poltava F",
    "OH Leuven W": "Leuven F",
    "Congo DR": "RD Congo",
    "Gambia": "Gambie",
    "Albania": "Albanie",
    "Norway": "Norvège",
    "Romania": "Roumanie",
    "Mauritania": "Mauritanie",
    "South Sudan": "Soudan du Sud",
    "Latvia": "Lettonie",
    "Manchester City": "Man City",
    "Club Brugge KV": "Club Brugge",
    "Lierse Kempenzonen": "k. Lierse SK",
    "AD Ceuta FC": "AD Ceuta",
    "Equatorial Guinea": "Guinée Equatoriale",
    "Zambia": "Zambie",
    "Chad": "Tchad",
    "Somalia": "Somalie",
    "Guinea": "Guinée",
    "Guinea-Bissau": "Guinée-Bissau",
    "Belgium": "Belgique",
    "Comoros":"Comores",
    "Central African Republic": "Centrafique",
    "Sporting CP": "Sporting",
    "Rep. Of Ireland": "Irlande",
    "Hungary": "Hongrie",
    "Austria": "Autriche",
    "Cyprus": "Chypre",
    "San Marino": "Saint-Martin",
    "CS Constantine": "Constantine",
    "Czech Republic": "République Tchèque",
    "Villa San Carlos": "San Carlos",
    "Spain": "Espagne",
    "Denmark": "Danemark",
    "Scotland": "Ecosse",
    "England": "Angleterre",
    "Eintracht Frankfurt": "Francfort",
    "VfL Wolfsburg": "Wolfsburg",
    "West Ham United": "West Ham",
    "Inter Miami CF": "Inter Miami",
    "Brazil": "Brésil",
    "The New Saints": "TNS",
    "Inter Club d'Escaldes": "Inter",
    "Valur Reykjavik": "Valur",
    "Brown DE Adrogue": "Brown Adrogue",
    "Los Angeles FC": "LAFC",
    "Lincoln Red Imps FC": "Lincoln",
    "Argentina": "Argentine",
    "Olimpija Ljubljana": "Olimpija",
    "FC Differdange 03": "Differdange",
    "Kairat Almaty": "Kairaty",
    "Cambodia": "Cambodge",
    "Saudi Arabia W ": "Arabie Saoudite",
    "Newcastle United": "Newcastle",
    "São Paulo FC": "São Paulo",
    "Japan": "Japon",
    "Uzbekistan": "Ouzbekistant",
    "South Korea": "Corée du Sud",
    "United States": "États-Unis",
    "Mexico": "Mexique",
    "Australia": "Australie",
    "Canada": "Canada",
    "Cliftonville FC": "Cliftonville",
    "Gangwon FC": "Gangwon",
    "Daejeon Citizen": "Daejeon",
    "Deportivo Armenio": "D. Armenio",
    "Senegal W": "Sénégal",
    "Pohang Steelers": "Pohang",
    "Jeju United FC": "Jeju United",
    "Jeonbuk Motors": "Jeonbuk",
    "Netherlands": "Pays-Bas",
    "Shonan Bellmare": "Shonan",
    "Cerezo Osaka": "C. Osaka",
    "Olympiacos FC": "Olympiakos",
    "Panathinaikos FC": "Panathinaikos",
    "AEK Athens FC": "AEK Athènes",
    "Croatia": "Croatie",
    "Napoli": "Naples",
    "Poland": "Pologne",
    "Serbia": "Serbie",
    "Turkey": "Turquie",
    "Morocco W": "Maroc",
    "Cameroon": "Cameroun",
    "Ivory Coast": "Côte d'Ivoire",
    "Hapoel Beer Sheva": "H. Beer Sheva",
    "Levski Sofia": "Levski",
    "Nigeria": "Nigéria",
    "Sheriff Tiraspol": "S. Tiraspol",
    "CFR 1907 Cluj": "CFR Cluj",
    "Wales": "Pays de Galles",
    "St Joseph S Fc": "St Josephs",
    "South Africa": "Afrique du Sud",
    "China": "Chine",
    "Zeljeznicar Sarajevo": "Zeljeznicar",
    "France W": "France",
    "Real Madrid W": "Real Madrid F",
    "Qatar": "Qatar",
    "Egypt": "Égypte",
    "Tunisia": "Tunisie",
    "Atlètic Club d'Escaldes": "Atletic Escaldes",
    "F91 Dudelange": "Dudelange",
    "Algeria": "Algérie",
    "Uruguay": "Uruguay",
    "Morocco": "Maroc",
    "Grêmio": "Grêmio",
    "Atlético Mineiro": "Atlético MG",
    "Internacional": "Internacional",
    "Santos FC": "Santos",
    "Al-Nassr FC": "Al Nassr",
    "Al-Ittihad Club": "Al Ittihad",
    "Al-Ahli Saudi FC": "Al Ahli",
    "Bangladesh": "Bangladesh",
    "PSV Eindhoven": "PSV",
    "Senegal": "Sénégal",
  };
  return translations[name] || name;
};

export default function MatchCard({ item }: { item: any }) {
  const router = useRouter();

  const { teams, goals, league, fixture } = item;

  const handlePress = () => {
    router.push(`/MatchDetailsScreen/${fixture.id}`);
  };

  return (
    <TouchableOpacity style={styles.card} onPress={handlePress}>
      <View style={styles.header}>
        <Image source={{ uri: league.logo }} style={styles.leagueLogo} />
        <Text style={styles.leagueText}>{league.name}</Text>
      </View>

      <View style={styles.teamsRow}>
        <View style={styles.team}>
          <Image source={{ uri: teams.home.logo }} style={styles.teamLogo} />
          <Text style={styles.teamName}>{translateTeamName(teams.home.name)}</Text>
        </View>

        <Text style={styles.score}>
          {goals.home !== null ? goals.home : "-"} - {goals.away !== null ? goals.away : "-"}
        </Text>

        <View style={styles.team}>
          <Image source={{ uri: teams.away.logo }} style={styles.teamLogo} />
          <Text style={styles.teamName}>{translateTeamName(teams.away.name)}</Text>
        </View>
      </View>

      <Text style={styles.dateText}>{new Date(fixture.date).toLocaleString("fr-FR")}</Text>
    </TouchableOpacity>
  );
}

const styles = StyleSheet.create({
  card: {
    backgroundColor: "#1e1e1e",
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
  },
  leagueLogo: {
    width: 18,
    height: 18,
    marginRight: 6,
  },
  leagueText: {
    color: "#aaa",
    fontSize: 12,
  },
  teamsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  team: {
    flexDirection: "row",
    alignItems: "center",
    width: "40%",
  },
  teamLogo: {
    width: 24,
    height: 24,
    marginRight: 6,
  },
  teamName: {
    color: "#fff",
    fontSize: 14,
    flexShrink: 1,
  },
  score: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  dateText: {
    color: "#777",
    fontSize: 12,
    marginTop: 8,
    textAlign: "center",
  },
});
